debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.tld"
watch = true
exposedbydefault = false

[acme]
email = "EMAIL_CH"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
# CA server to use
# Uncomment the line to run on the staging let's encrypt server
# Comment out to go to prod
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
caServer = "https://acme-staging.api.letsencrypt.org/directory"


[acme.dnsChallenge]
  provider = "rfc2136"
  delayBeforeCheck = 0

[[acme.domains]]
   main = "domain.tld"
[[acme.domains]]
   main = "*.domain.tld"
